create Database Exam1
use Exam1
CREATE TABLE EMPLOYEES
(
EMPID INT NOT NULL,
NAME VARCHAR(255)
SALARY INT,
DEPTNO INT IDENTITY (10,10),
CONSTRAINT CHK_SAL CHECK (SALARY >=5000 AND SALARY<=50000)
)
select * from EMPLOYEES
